"""made user_game_reviews association table

Revision ID: 54c2cd204448
Revises: d1a8a1daf3b2
Create Date: 2024-07-23 22:44:05.408099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c2cd204448'
down_revision = 'd1a8a1daf3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_game_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_user_game_reviews_game_id_games')),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_user_game_reviews_review_id_reviews')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_game_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_game',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='fk_user_game_game_id_games'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_game_user_id_users'),
    sa.PrimaryKeyConstraint('user_id', 'game_id')
    )
    op.drop_table('user_game_reviews')
    # ### end Alembic commands ###
