"""Update review model

Revision ID: d3e58cb85466
Revises: 4bc1bf1d5b8e
Create Date: 2024-07-22 00:03:57.147857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e58cb85466'
down_revision = '4bc1bf1d5b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pfp', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_reviews_username_users'), 'users', ['username'], ['username'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_pfp_users'), 'users', ['pfp'], ['pfp_image_url'])
        batch_op.create_foreign_key(batch_op.f('fk_reviews_title_games'), 'games', ['title'], ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reviews_title_games'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_pfp_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_reviews_username_users'), type_='foreignkey')
        batch_op.drop_column('title')
        batch_op.drop_column('pfp')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
