"""Remove extra foreign keys

Revision ID: d73d7ef33e5a
Revises: d3e58cb85466
Create Date: 2024-07-22 00:05:40.015322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73d7ef33e5a'
down_revision = 'd3e58cb85466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reviews_username_users', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_pfp_users', type_='foreignkey')
        batch_op.drop_constraint('fk_reviews_title_games', type_='foreignkey')
        batch_op.drop_column('pfp')
        batch_op.drop_column('username')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('pfp', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key('fk_reviews_title_games', 'games', ['title'], ['title'])
        batch_op.create_foreign_key('fk_reviews_pfp_users', 'users', ['pfp'], ['pfp_image_url'])
        batch_op.create_foreign_key('fk_reviews_username_users', 'users', ['username'], ['username'])

    # ### end Alembic commands ###
